Develop express button
krokedil/klarna-payments-for-woocommerce pull request #273
Opened 2022-05-06 23:59 UTC by montazarr

2022-05-09 09:34 UTC, MichaelBengtsson requested changes

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +					'placeholder' => __( 'A value between 145 and 500 (measured in px)', 'klarna-payments-for-woocommerce' ),
Maybe change this to say pixels instead of px? To make it clearer.

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +					'placeholder' => __( 'A value between 35 and 60 (measured in px)', 'klarna-payments-for-woocommerce' ),
Same as above

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +					'title' => 'Express Checkout (aka Express Button)',
Remove aka, Express Checkout (Express Button)

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +				'express_data_theme'  => array(
Add a description to this setting to clarify what it is/does

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +					'title'   => __( 'Shape', 'klarna-payments-for-woocommerce' ),
Maybe change to style instead of shape? Or is this how Klarna describes it in their docs?

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +					'defualt'     => '',
Misspelled default.

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +					'defualt'     => '',
Misspelled default.

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +				'express_data_width'  => array(
Change the desc_tip and placeholder to both be a description instead. For example
'description' => __( 'A value between 145 and 500 (measured in px). Leave blank for default width.', 'klarna-payments-for-woocommerce' ),

2022-05-09 09:34 UTC, MichaelBengtsson commented on classes/class-kp-assets.php
> +	public function enqueue_express_button() {
possibly split this function into two, one for the script and one for the style. Just to keep them separated to make maintenance easier.

2022-05-09 09:34 UTC, MichaelBengtsson commented on includes/kp-functions.php
> +	if ( method_exists( 'WC_Geolocation', 'geolocate_ip' ) && ! empty( WC_Geolocation::geolocate_ip()['country'] ) ) {
Instead of using the geolocation you should use the customer location instead. This is because some stores will want to set the default for this to different things.

wc_get_customer_default_location() and then check the country returned.
https://woocommerce.wp-a2z.org/oik_api/wc_get_customer_default_location/

This will check settings, and possibly use the geolocation to get the country in the end, but we let WooCommerce handle that logic.

2022-05-09 11:01 UTC, mntzrr commented on classes/admin/class-kp-form-fields.php
> +					'title'   => __( 'Shape', 'klarna-payments-for-woocommerce' ),
Klarna refers to it as [_shape_](https://docs.klarna.com/express-button/button-customization/button-shapes/).

2022-05-09 11:03 UTC, montazarr commented on classes/admin/class-kp-form-fields.php
> +					'defualt'     => '',
Good catch!

2022-05-09 11:22 UTC, MichaelBengtsson commented on classes/admin/class-kp-form-fields.php
> +					'title'   => __( 'Shape', 'klarna-payments-for-woocommerce' ),
In that case keep it like this!

2022-05-10 08:38 UTC, montazarr commented on includes/kp-functions.php
> +	if ( method_exists( 'WC_Geolocation', 'geolocate_ip' ) && ! empty( WC_Geolocation::geolocate_ip()['country'] ) ) {
Since `wc_get_customer_default_location` will use Geolocation (if available), I'll remove the geolocation code altogether instead.

2022-05-20 06:14 UTC, MichaelBengtsson approved these changes

2022-05-20 12:32 UTC, MichaelBengtsson approved these changes

2022-07-12 10:11 UTC, merged