Add support for WC subscriptions
krokedil/klarna-payments-for-woocommerce pull request #337
Opened 2023-07-11 17:38 UTC by mntzrr

Related task: https://app.clickup.com/t/1p1z7j

2023-07-25 08:57 UTC, NiklasHogefjord approved these changes

2023-08-30 13:33 UTC, MichaelBengtsson commented on classes/class-kp-subscriptions.php
> +		public function set_subscription_as_captured( $order_id ) {
Missing block comment for function

2023-08-30 14:14 UTC, MichaelBengtsson commented on classes/requests/class-kp-requests-patch.php
> +	 * Qliro_One_Request_Post constructor.
Fix the comment here. Wrong class name

2023-08-30 14:14 UTC, MichaelBengtsson commented on classes/requests/class-kp-requests-patch.php
> +	 * Qliro_One_Request_Post constructor.
Seems like we have the same in the post class as well, so can you fix that too while you are doing this one?

2023-08-30 14:17 UTC, MichaelBengtsson requested changes
Looks good except for the block comment on the request files.

2023-08-31 07:45 UTC, merged