Develop api endpoints
krokedil/klarna-payments-for-woocommerce pull request #436
Opened 2024-12-17 08:06 UTC by anyakro

**Non tested refactoring of the extracting of the unavailable features.** Since yesterday I'm only receiving this from the API: "Cannot fetch data from MPCS", which makes me unable to test the changes. The same core functionality was working as expected for the front-end on change update and from the saved option on page load, before that.

Known needed modifications: The mapping of the feature ids needs to be updated or rebuilt.

Test API credentials needs to be used for the request to work at the moment.

2025-01-09 16:30 UTC, anyakro commented
Added JS temporary storage of credentials, allowance of errors to be returned for one set of credentials together with returning a general collection of errors, and other small fixes discussed yesterday should be fixed.

I also realized that a restructuring of the extraction of unavailable features logic was needed to handle the "bundling" of features, i.e. if any feature pertaining to payments should be shown, show the KP feature etc.

I think this is closer to the solution you first imagined, which was probably the best one to begin with :)

2025-01-22 09:40 UTC, MichaelBengtsson requested changes

2025-01-22 09:40 UTC, MichaelBengtsson commented on includes/kp-functions.php
> +	error_log( print_r( kp_map_unavailable_features( $collected_features ), true ) );
Remove the error log

2025-01-22 09:40 UTC, MichaelBengtsson commented on includes/kp-functions.php
> +function kp_get_unavailable_feature_ids( $country_credentials ) {
Missing function comment

2025-01-22 09:40 UTC, MichaelBengtsson commented on classes/class-kp-settings-saved.php
> +		update_option( 'kp_unavailable_feature_ids', $unavailable_features['feature_ids'] );
This is for a fresh install saved as a empty string causing errors in other places in the code. Please update this to never store it as a empty value, but rather as a empty array in that case.

2025-02-05 14:25 UTC, MichaelBengtsson approved these changes

2025-02-05 14:27 UTC, MichaelBengtsson commented
@anyakro Looks good so far, but i will wait with merging this until we get a ok from Klarna for this

2025-02-17 14:21 UTC, merged